title: Yakhyo Valikhujaev
description: >
  MSc in CS from Gachon University 🎓<br><br>
  BSc in CS from TUIT 🏅<br><br>
  <a href="https://yakhyo.github.io/yakhyo/assets/resumes/yakhyo_cv.pdf">
    <img src="assets/icons/download-pdf.png" alt="Dowload CV" style="height:40px; width:auto;">
  </a>

logo: assets/logo.png
show_downloads: False
google_analytics: G-ET5KWGXJ4B
remote_theme: pages-themes/minimal@v0.2.0

github:
  is_user_page: false
  is_project_page: false
  owner: yakhyo

exclude:

plugins:
  - jekyll-remote-theme
